### ISSUE TITLE
Social networks icons are hidden by AdBlock Plus

### ISSUE THREAD

**Issue by jpoliva** [makinacorpus/ortho44#1]
![adp_hidden_icons](https://f.cloud.github.com/assets/4365784/1154499/f25c5f74-1f47-11e3-8804-d90ad7b8e5e2.png)
Tested with Firefox 23 on Linux

**Comment by ebrehault** [comment]
It works fine with a vanilla AdBlock Plus on Firefox 23 on Linux.
Do you have any specific parameters in your AdBlocks settings ?

**Comment by jpoliva** [comment]
Here are my settings:

![adp_filters](https://f.cloud.github.com/assets/4365784/1154502/12b57896-1f48-11e3-8aa1-066b91ddb85d.png)

**Comment by fredericbonifas** [comment]
@jpoliva Do you still have this problem ?

**Comment by jpoliva** [comment]
It works all right now.
