### ISSUE TITLE
Add comparison state to URL

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/ortho44#2]
Currently, the current comparison cannot be printed, shared, etc.

**Comment by leplatrem** [comment]
Works for url sharing, but not for printing apparently

http://screamshot.makina-corpus.net/capture/?render=html&waitfor=.map-initialized&url=http%3A%2F%2Fmakinacorpus.github.io%2Fortho44%2F%2315%2F47.5232%2F-1.4082!1850

...looks like the second map is here, but not overlapping half of the first one

**Comment by ebrehault** [comment]
no idea why the same css produce a 50-50% rendering in a browser and 75%-25% with screamshot...

**Comment by leplatrem** [comment]
You don't have any `display: block` that would disable overlapping ?
The resulting layout looks extremely wide, that could also a source of difference with screens...

(my 2 cents)
